# 範例 : 計程車費率預測
https://www.kaggle.com/c/new-york-city-taxi-fare-prediction
***
- 使用程車費率預測競賽練習時間欄位處理

In [1]:
# 做完特徵工程前的所有準備
import pandas as pd
import numpy as np
import datetime
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor

data_path = 'data/'
df = pd.read_csv(data_path + 'taxi_data1.csv')

train_Y = df['fare_amount']
df = df.drop(['fare_amount'] , axis=1)
df.head()

E:\Anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")
E:\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2011-10-21 23:54:10 UTC,-73.990580,40.761071,-73.981128,40.758634,2
1,2015-02-03 10:42:03 UTC,-73.988403,40.723431,-73.989647,40.741695,1
2,2014-03-16 18:58:58 UTC,-74.015785,40.715110,-74.012029,40.707888,2
3,2009-06-13 16:10:54 UTC,-73.977322,40.787275,-73.958030,40.778838,3
4,2014-06-12 03:25:56 UTC,-73.989683,40.729717,-73.982490,40.761887,3

In [2]:
# 時間特徵分解方式:使用datetime
df['pickup_datetime'] = df['pickup_datetime'].apply(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d %H:%M:%S UTC'))
df['pickup_year'] = df['pickup_datetime'].apply(lambda x: datetime.datetime.strftime(x, '%Y')).astype('int64')
df['pickup_month'] = df['pickup_datetime'].apply(lambda x: datetime.datetime.strftime(x, '%m')).astype('int64')
df['pickup_day'] = df['pickup_datetime'].apply(lambda x: datetime.datetime.strftime(x, '%d')).astype('int64')
df['pickup_hour'] = df['pickup_datetime'].apply(lambda x: datetime.datetime.strftime(x, '%H')).astype('int64')
df['pickup_minute'] = df['pickup_datetime'].apply(lambda x: datetime.datetime.strftime(x, '%M')).astype('int64')
df['pickup_second'] = df['pickup_datetime'].apply(lambda x: datetime.datetime.strftime(x, '%S')).astype('int64')
df.head()

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_year,pickup_month,pickup_day,pickup_hour,pickup_minute,pickup_second
0,2011-10-21 23:54:10,-73.990580,40.761071,-73.981128,40.758634,2,2011,10,21,23,54,10
1,2015-02-03 10:42:03,-73.988403,40.723431,-73.989647,40.741695,1,2015,2,3,10,42,3
2,2014-03-16 18:58:58,-74.015785,40.715110,-74.012029,40.707888,2,2014,3,16,18,58,58
3,2009-06-13 16:10:54,-73.977322,40.787275,-73.958030,40.778838,3,2009,6,13,16,10,54
4,2014-06-12 03:25:56,-73.989683,40.729717,-73.982490,40.761887,3,2014,6,12,3,25,56

In [3]:
# 將結果使用線性迴歸 / 梯度提升樹分別看結果
df_temp = df.drop(['pickup_datetime'] , axis=1)
scaler = MinMaxScaler()
train_X = scaler.fit_transform(df_temp)
Linear = LinearRegression()
print(f'Linear Reg Score : {cross_val_score(Linear, train_X, train_Y, cv=5).mean()}')
GDBT = GradientBoostingRegressor()
print(f'Gradient Boosting Reg Score : {cross_val_score(GDBT, train_X, train_Y, cv=5).mean()}')

Linear Reg Score : 0.026876871475636888
Gradient Boosting Reg Score : 0.7131980113053118

# 作業1
* 對照範例，試著加入星期幾 (day of week) 與第幾周 (week of year) 這兩項特徵，  
看看結果會比原本只有時間特徵分解的結果更好或更差?

In [6]:
df_temp

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_year,pickup_month,pickup_day,pickup_hour,pickup_minute,pickup_second,week_of_year
0,-73.990580,40.761071,-73.981128,40.758634,2,2011,10,21,23,54,10,42.0
1,-73.988403,40.723431,-73.989647,40.741695,1,2015,2,3,10,42,3,6.0
2,-74.015785,40.715110,-74.012029,40.707888,2,2014,3,16,18,58,58,11.0
3,-73.977322,40.787275,-73.958030,40.778838,3,2009,6,13,16,10,54,24.0
4,-73.989683,40.729717,-73.982490,40.761887,3,2014,6,12,3,25,56,24.0
5,-73.997631,40.721805,-74.009757,40.709941,1,2011,7,16,1,19,59,28.0
6,-73.954743,40.789303,-73.964755,40.773345,1,2009,6,27,18,15,0,26.0
7,-73.982279,40.764668,-73.990323,40.756427,1,2009,1,23,20,38,16,4.0
8,-73.965039,40.769972,-73.955365,40.779438,1,2010,8,9,14,46,3,32.0
9,-73.986570,40.734727,-74.003757,40.741951,1,2011,9,29,21,56,45,39.0
10,-73.953742,40.774040,-73.969870,40.785605,1,2009,2,9,22,26,0,7.0
11,-73.982057,40.768790,-73.949467,40.830230,1,2010,11,3,21,7,0,44.0
12,-73.983368,40.727033,-73.953655,40.666835,4,2009,11,23,5,18,0,48.0
13,-74.005307,40.728124,-73.979042,40.741986,1,2012,4,2,21,8,2,14.0
14,-73.970473,40.783983,-73.967860,40.762692,1,2009,12,14,20,28,45,51.0
15,-73.951788,40.714289,-73.952272,40.694019,2,2014,3,30,1,52,38,13.0
16,-73.999353,40.761494,-73.953128,40.768081,1,2009,7,1,3,24,53,27.0
17,-74.001532,40.730875,-73.978048,40.764719,1,2013,8,1,1,0,25,31.0
18,-73.966994,40.757627,-73.967327,40.766001,1,2012,3,17,10,39,5,11.0
19,-73.967032,40.803832,-73.973962,40.754712,2,2013,11,1,20,41,0,44.0
20,-73.988503,40.731349,-73.979510,40.748828,1,2014,4,21,17,48,35,17.0
21,-73.958500,40.810140,-73.978187,40.778183,4,2012,1,7,17,53,0,1.0
22,-73.966323,40.761512,-73.957015,40.768288,1,2011,6,16,15,6,0,24.0
23,-73.989962,40.767048,-73.950755,40.776633,1,2011,3,5,20,25,0,9.0
24,-73.958430,40.781613,-73.985932,40.770163,1,2012,10,8,9,9,39,41.0
25,-73.979752,40.766000,-73.985705,40.756777,1,2014,5,21,18,46,0,21.0
26,-73.994117,40.759050,-73.942337,40.847027,1,2014,2,11,21,21,0,7.0
27,-73.980308,40.780442,-73.972903,40.795217,5,2011,7,9,23,12,0,27.0
28,-73.980436,40.770263,-73.953017,40.783132,1,2011,12,14,12,3,14,50.0
29,-73.951540,40.769698,-73.966601,40.753667,1,2012,2,12,12,9,15,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4970,-73.982535,40.745528,-73.970325,40.799040,1,2012,7,14,21,36,0,28.0
4971,-73.994720,40.745266,-73.951874,40.777031,1,2015,3,24,21,15,30,13.0
4972,-74.007568,40.743445,-74.009453,40.715368,4,2011,2,21,21,9,0,8.0
4973,-73.988347,40.720062,-73.984237,40.744293,3,2012,10,28,3,46,39,43.0
4974,-74.003000,40.748896,-73.993130,40.762910,1,2013,9,12,22,28,17,37.0
4975,-73.982075,40.755006,-73.962513,40.778304,1,2010,7,18,10,51,22,28.0
4976,-73.853805,40.727235,-73.862738,40.729588,5,2009,8,12,10,20,0,33.0
4977,-73.991290,40.750211,-74.006304,40.722786,1,2010,12,3,11,21,47,48.0
4978,-74.007162,40.711847,-74.012580,40.701522,1,2009,10,3,13,8,0,40.0
4979,-73.977730,40.786848,-73.977370,40.775877,1,2009,5,1,23,7,0,18.0
4980,-73.967935,40.803050,-73.965573,40.764447,1,2009,2,7,20,28,46,6.0
4981,-73.961487,40.774535,-73.889445,40.819582,1,2011,10,24,14,9,0,43.0
4982,-73.863480,40.769920,-73.966133,40.757999,1,2015,3,16,20,21,31,12.0
4983,-73.957769,40.773766,-73.978916,40.773361,1,2011,7,27,10,43,46,30.0
4984,-73.991764,40.759287,-73.988162,40.732078,3,2011,2,6,11,58,46,5.0
4985,-74.007777,40.715137,-74.004057,40.725677,1,2013,12,20,2,11,0,51.0
4986,-73.996112,40.726045,-73.983083,40.756667,1,2014,2,1,13,33,17,5.0
4987,-73.975698,40.756953,-73.984026,40.757036,1,2009,12,18,18,3,46,51.0
4988,-73.990323,40.752555,-73.991157,40.731852,6,2012,11,5,14,58,0,45.0
4989,-73.965067,40.755190,-73.965067,40.755190,5,2013,12,24,18,36,0,52.0
4990,-73.975028,40.765580,-73.989997,40.751650,1,2012,12,2,12,21,13,48.0
4991,-73.991309,40.739068,-73.995768,40.726276,1,2009,4,11,19,24,50,15.0
4992,-73.957620,40.782134,-73.973613,40.750718,1,2014,12,1,19,59,19,49.0
4993,-73.973512,40.754700,-73.981157,40.737545,1,2014,9,29,18,59,0,40.0
4994,-73.982043,40.774592,-73.976149,40.782166,1,2009,8,13,14,16,40,33.0
4995,-73.994150,40.761397,-73.986840,40.759202,1,2011,12,23,19,7,0,51.0
4996,-73.986767,40.729937,-73.977022,40.726482,1,2009,8,26,18,19,41,35.0
4997,-73.984612,40.732297,-73.995004,40.750059,1,2010,10,25,6,5,21,43.0
4998,-73.958460,40.773415,-73.953445,40.782598,1,2010,2,16,16,57,0,7.0
4999,-73.965193,40.759520,-73.991758,40.744213,4,2009,2,18,17,1,5,8.0

In [5]:
# 加入星期幾與第幾周兩個特徵
day_of_week = np.array([])
week_of_year = np.array([])
for i in range(df.shape[0]):
    day_of_week=np.append(day_of_week,datetime.datetime(df['pickup_year'][i],df['pickup_month'][i],df['pickup_day'][i]).weekday())
    week_of_year=np.append(week_of_year,datetime.datetime(df['pickup_year'][i],df['pickup_month'][i],df['pickup_day'][i]).isocalendar()[1])
df['day_of_week'] = day_of_week
df_temp['week_of_year'] = week_of_year
# import math
# df['day_cycle'] = df['pickup_hour']/12 + df['pickup_minute']/720 + df['pickup_second']/43200
# df['day_cycle'] = df['day_cycle'].map(lambda x:math.sin(x*math.pi))
# df.head()
# df.head()

In [40]:
# 將結果使用線性迴歸 / 梯度提升樹分別看結果
df_temp = df.drop(['pickup_datetime'] , axis=1)
train_X = scaler.fit_transform(df_temp)
print(f'Linear Reg Score : {cross_val_score(Linear, train_X, train_Y, cv=5).mean()}')
print(f'Gradient Boosting Reg Score : {cross_val_score(GDBT, train_X, train_Y, cv=5).mean()}')

Linear Reg Score : 0.026171253679798646
Gradient Boosting Reg Score : 0.7089779164598267

In [41]:
# 加上"日週期"特徵 (參考講義"週期循環特徵")
import math
df['day_cycle'] = df['pickup_hour']/12 + df['pickup_minute']/720 + df['pickup_second']/43200
df['day_cycle'] = df['day_cycle'].map(lambda x:math.sin(x*math.pi))
df.head()

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_year,pickup_month,pickup_day,pickup_hour,pickup_minute,pickup_second,day_cycle,day_of_week
0,2011-10-21 23:54:10,-73.990580,40.761071,-73.981128,40.758634,2,2011,10,21,23,54,10,-0.025450,4.0
1,2015-02-03 10:42:03,-73.988403,40.723431,-73.989647,40.741695,1,2015,2,3,10,42,3,0.333601,1.0
2,2014-03-16 18:58:58,-74.015785,40.715110,-74.012029,40.707888,2,2014,3,16,18,58,58,-0.967083,6.0
3,2009-06-13 16:10:54,-73.977322,40.787275,-73.958030,40.778838,3,2009,6,13,16,10,54,-0.888817,5.0
4,2014-06-12 03:25:56,-73.989683,40.729717,-73.982490,40.761887,3,2014,6,12,3,25,56,0.782427,3.0

In [42]:
# 將結果使用線性迴歸 / 梯度提升樹分別看結果
df_temp = df.drop(['pickup_datetime'] , axis=1)
train_X = scaler.fit_transform(df_temp)
print(f'Linear Reg Score : {cross_val_score(Linear, train_X, train_Y, cv=5).mean()}')
print(f'Gradient Boosting Reg Score : {cross_val_score(GDBT, train_X, train_Y, cv=5).mean()}')

Linear Reg Score : 0.026171253679798646
Gradient Boosting Reg Score : 0.7093181063244579

# 作業2
* 對照範例的日週期效果，試著參考投影片完成年週期與周週期的特徵 (也可以用你自己想到的方式)，  
看看結果會比範例中的結果更好或更差?

In [45]:
# 加上"年週期"與"周週期"特徵
df['year_cycle'] = df['pickup_month']/6 + df['pickup_day']/180
df['year_cycle'] = df['year_cycle'].map(lambda x:math.cos(x*math.pi))
df['week_cycle'] = df['day_of_week']/3.5 + df['pickup_hour']/84
df['week_cycle'] = df['week_cycle'].map(lambda x:math.sin(x*math.pi))

In [46]:
# 將結果使用線性迴歸 / 梯度提升樹分別看結果
df_temp = df.drop(['pickup_datetime'] , axis=1)
train_X = scaler.fit_transform(df_temp)
print(f'Linear Reg Score : {cross_val_score(Linear, train_X, train_Y, cv=5).mean()}')
print(f'Gradient Boosting Reg Score : {cross_val_score(GDBT, train_X, train_Y, cv=5).mean()}')

Linear Reg Score : 0.026035847087468467
Gradient Boosting Reg Score : 0.7084380710921268